### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by jbkey2015** [nss-evening-cohort-10/chatty-group-project-pond-frogs#19]
## User Story
As a developer, I would like to have a rough idea of the site layout and design as I build it. 

## AC
WHEN I open this project,
THEN I would like to see a screenshot of the page layout mockup

## Dev Notes
* Navbar should be at top of page
* Logo should be top-left aligned of navbar
* `clear` button should be to far right of navbar
* input field should fill top of space between logo and clear button
* underneath logo should be two checkboxes, `large text` and `dark theme`
* a settings cog should be under `clear` button
* body should display 5 message bubbles with timestamps and delete `x` button

**Comment by mariabrock** [comment]
![chatty mainview](https://user-images.githubusercontent.com/54127296/66880454-a091a100-ef88-11e9-9f18-7aab8b81c7f5.PNG)
![clapback logo](https://user-images.githubusercontent.com/54127296/66880457-a5eeeb80-ef88-11e9-8faf-22b88701a0aa.PNG)
![input-clear-gear-checks](https://user-images.githubusercontent.com/54127296/66880462-a8e9dc00-ef88-11e9-8a3e-0272fb0341a2.PNG)
![message-bubbles](https://user-images.githubusercontent.com/54127296/66880464-ac7d6300-ef88-11e9-8c89-3181e42edb5d.PNG)
![standard colors](https://user-images.githubusercontent.com/54127296/66880466-af785380-ef88-11e9-8736-ebcdcae023c6.PNG)

**Comment by jacob-bw** [comment]
👍
