### ISSUE TITLE
Seed Data

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-10/chatty-group-project-pond-frogs#3]
## User Story
As a developer, in order to have something on the page, I would like some seed data

## AC
**Given** A developer navigated to your repo
**Then** they should see a file called `db/messages.js`
**And** this file should have seed data for 5 messages

## Dev Notes
* create module for Seed Data containing 5 pre-generated cards/speech bubbles
* seed data should be 5 unique messages, 4 jokes about web dev, 1 instructions bubble

**Comment by jacob-bw** [comment]
explore npm package https://www.npmjs.com/package/devpun

possibly worthwhile/fun to install this extension and then generate seed data to pull from this package, but limit pre-printed cards to only 4 random selections + instructions/intro card
